import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getFirestore, collection, doc, onSnapshot, setDoc } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDtQ3pECcZETIoI4QTV5G-7_QcoRvVGHL4",authDomain:"dannistreffturnier.firebaseapp.com",projectId:"dannistreffturnier",storageBucket:"dannistreffturnier.firebasestorage.app",messagingSenderId:"829873084116",appId:"1:829873084116:web:683bbf1ea3e58f1a4ecd41"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);const db=getFirestore(app);
const $=id=>document.getElementById(id);const clone=v=>JSON.parse(JSON.stringify(v));
const istTv=new URLSearchParams(location.search).get("tv")==="true";
let istAdmin=false;try{istAdmin=(JSON.parse(localStorage.getItem("dart11enLogin")||"null")?.rolle||"").toLowerCase()==="admin"}catch{}
let teilnehmer=[];let daten=null;let speicherTimer=null;let entwurfRegeln={ko1:[1,2],ko2:[3,4]};

function spielName(p){return p.nickname||[p.vorname,p.nachname].filter(Boolean).join(" ")}
function mischen(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function paarungen(spieler,prefix){const out=[];let n=1;for(let i=0;i<spieler.length;i++)for(let j=i+1;j<spieler.length;j++)out.push({id:`${prefix}-${n++}`,a:spieler[i],b:spieler[j],scoreA:null,scoreB:null});return out}
function gruppenErstellen(namen,anzahl){const gs=Array.from({length:anzahl},(_,i)=>({id:String.fromCharCode(65+i),spieler:[],spiele:[]}));mischen(namen).forEach((n,i)=>gs[i%anzahl].spieler.push(n));gs.forEach(g=>g.spiele=paarungen(g.spieler,`G${g.id}`));return gs}
function siegLegs(){return Math.ceil((daten?.bestOf||3)/2)}
function matchErgebnis(m){const z=siegLegs();if(m.scoreA===z&&m.scoreB<z)return{gewinner:m.a,verlierer:m.b};if(m.scoreB===z&&m.scoreA<z)return{gewinner:m.b,verlierer:m.a};return null}
function tabelle(g){const rows=new Map(g.spieler.map(n=>[n,{name:n,sp:0,s:0,n:0,lf:0,lg:0,diff:0,p:0}]));g.spiele.forEach(m=>{const e=matchErgebnis(m);if(!e)return;const a=rows.get(m.a),b=rows.get(m.b);a.sp++;b.sp++;a.lf+=m.scoreA;a.lg+=m.scoreB;b.lf+=m.scoreB;b.lg+=m.scoreA;a.diff=a.lf-a.lg;b.diff=b.lf-b.lg;if(e.gewinner===m.a){a.s++;b.n++;a.p+=2}else{b.s++;a.n++;b.p+=2}});return [...rows.values()].sort((a,b)=>b.p-a.p||b.diff-a.diff||b.lf-a.lf||a.name.localeCompare(b.name,"de"))}
function alleGruppenFertig(){return daten?.gruppen?.every(g=>g.spiele.every(m=>matchErgebnis(m)))||false}
function naechsteZweierzahl(n){let z=2;while(z<n)z*=2;return z}
function koErstellen(spieler,id){const feld=naechsteZweierzahl(Math.max(2,spieler.length));const slots=[...spieler,...Array(feld-spieler.length).fill("Freilos")];const runden=[];for(let r=0,anz=feld/2;anz>=1;r++,anz/=2)runden.push(Array.from({length:anz},(_,i)=>({id:`K${id}-${r+1}-${i+1}`,a:null,b:null,scoreA:null,scoreB:null})));runden[0].forEach((m,i)=>{m.a=slots[i*2]||"Freilos";m.b=slots[i*2+1]||"Freilos"});return{id,runden}}
function koErgebnis(m){if(m.a==="Freilos"&&m.b==="Freilos")return{gewinner:"Freilos"};if(m.a==="Freilos"&&m.b)return{gewinner:m.b};if(m.b==="Freilos"&&m.a)return{gewinner:m.a};return matchErgebnis(m)}
function koWege(ko){const alt=new Map(ko.runden.flat().map(m=>[m.id,clone(m)]));ko.runden.slice(1).flat().forEach(m=>{m.a=null;m.b=null;m.scoreA=null;m.scoreB=null});ko.runden.forEach((runde,r)=>runde.forEach((m,i)=>{const old=alt.get(m.id);if(old&&old.a===m.a&&old.b===m.b){m.scoreA=old.scoreA;m.scoreB=old.scoreB}const e=koErgebnis(m);if(e&&r<ko.runden.length-1){const z=ko.runden[r+1][Math.floor(i/2)];const feld=i%2?"b":"a";z[feld]=e.gewinner;const zo=alt.get(z.id);if(zo&&zo.a===z.a&&zo.b===z.b){z.scoreA=zo.scoreA;z.scoreB=zo.scoreB}}}))}
function qualifizierte(pos){const out=[];daten.gruppen.forEach(g=>{const tab=tabelle(g);pos.forEach(p=>{if(tab[p-1])out.push({name:tab[p-1].name,gruppe:g.id,platz:p})})});return out}
function koPhasenErstellen(){if(!alleGruppenFertig()){alert("Bitte zuerst alle Gruppenspiele abschließen.");return}const sets=[daten.regeln.ko1,daten.regeln.ko2].slice(0,daten.anzahlKo);daten.koPhasen=sets.map((pos,i)=>{const q=qualifizierte(pos);const sortiert=[];const max=Math.max(0,...pos);for(let p=1;p<=max;p++){const stufe=mischen(q.filter(x=>x.platz===p));sortiert.push(...stufe.map(x=>x.name))}return koErstellen(sortiert,i+1)});speichern();renderAlles()}
function speichern(){localStorage.setItem("dart11enGruppenKo",JSON.stringify(daten));clearTimeout(speicherTimer);speicherTimer=setTimeout(()=>setDoc(doc(db,"turnierLive","gruppenTurnier"),{datenJson:JSON.stringify(daten),aktualisiert:Date.now()}).catch(console.error),250)}
function scoreSelect(wert,onchange){const s=document.createElement("select");s.innerHTML='<option value="">–</option>'+Array.from({length:siegLegs()+1},(_,i)=>`<option value="${i}">${i}</option>`).join("");s.value=wert??"";s.onchange=()=>onchange(s.value===""?null:Number(s.value));return s}
function regelOptionen(box,key){if(!box)return;box.replaceChildren();const quelle=daten?.regeln||entwurfRegeln;for(let p=1;p<=8;p++){const l=document.createElement("label"),c=document.createElement("input");c.type="checkbox";c.checked=quelle[key]?.includes(p)||false;c.onchange=()=>{const ziel=daten?.regeln||entwurfRegeln;const arr=new Set(ziel[key]||[]);c.checked?arr.add(p):arr.delete(p);ziel[key]=[...arr].sort((a,b)=>a-b);if(daten){daten.koPhasen=[];speichern();renderAlles()}};l.append(c,document.createTextNode(`Platz ${p}`));box.append(l)}}
function renderConfig(){const mode=$("turnierModus");if(mode)mode.value=daten?.modus||localStorage.getItem("dart11enTurnierModus")||"doppelko";const panel=$("gruppenKonfiguration");panel?.classList.toggle("modus-versteckt",mode?.value!=="gruppenko");if(daten){$("gruppenAnzahl").value=daten.anzahlGruppen;$("koAnzahl").value=daten.anzahlKo;$("gruppenBestOf").value=daten.bestOf}const koAnzahl=daten?.anzahlKo||Number($("koAnzahl")?.value||2);$("ko2RegelBox")?.classList.toggle("modus-versteckt",koAnzahl<2);regelOptionen($("ko1Plaetze"),"ko1");regelOptionen($("ko2Plaetze"),"ko2")}
function renderGruppe(g,admin=false){const card=document.createElement("article");card.className="gruppe-card";card.innerHTML=`<h3>Gruppe ${g.id}</h3>`;if(admin){const players=document.createElement("div");players.className="gruppe-spieler";g.spieler.forEach(name=>{const z=document.createElement("div");z.className="gruppe-spieler-zeile";const b=document.createElement("strong");b.textContent=name;const s=document.createElement("select");daten.gruppen.forEach(x=>s.add(new Option(`Gruppe ${x.id}`,x.id)));s.value=g.id;s.onchange=()=>{const ziel=daten.gruppen.find(x=>x.id===s.value);g.spieler=g.spieler.filter(n=>n!==name);ziel.spieler.push(name);daten.gruppen.forEach(x=>x.spiele=paarungen(x.spieler,`G${x.id}`));daten.koPhasen=[];speichern();renderAlles()};z.append(b,s);players.append(z)});card.append(players)}const table=document.createElement("table");table.className="gruppen-tabelle";table.innerHTML='<thead><tr><th>#</th><th>Spieler</th><th>Sp</th><th>S</th><th>N</th><th>Legs</th><th>Diff</th><th>P</th></tr></thead>';const body=document.createElement("tbody");const q=new Set([...(daten.regeln.ko1||[]),...(daten.anzahlKo>1?daten.regeln.ko2:[])]);tabelle(g).forEach((r,i)=>{const tr=document.createElement("tr");if(q.has(i+1))tr.className="qualifiziert";tr.innerHTML=`<td>${i+1}</td><td>${r.name}</td><td>${r.sp}</td><td>${r.s}</td><td>${r.n}</td><td>${r.lf}:${r.lg}</td><td>${r.diff}</td><td>${r.p}</td>`;body.append(tr)});table.append(body);card.append(table);if(admin){const games=document.createElement("div");games.className="gruppen-spiele";g.spiele.forEach(m=>{const a=document.createElement("article");a.className="gruppen-match";a.innerHTML=`<div class="gruppen-match-kopf"><span>${m.id}</span><span>Best of ${daten.bestOf}</span></div>`;const row=document.createElement("div");row.className="gruppen-score";const na=document.createElement("span");na.textContent=m.a;const nb=document.createElement("span");nb.textContent=m.b;const sep=document.createElement("b");sep.textContent=":";const sa=scoreSelect(m.scoreA,v=>{m.scoreA=v;if(v===siegLegs()&&m.scoreB>=siegLegs())m.scoreB=null;daten.koPhasen=[];speichern();renderAlles()});const sb=scoreSelect(m.scoreB,v=>{m.scoreB=v;if(v===siegLegs()&&m.scoreA>=siegLegs())m.scoreA=null;daten.koPhasen=[];speichern();renderAlles()});row.append(na,sa,sep,sb,nb);a.append(row);games.append(a)});card.append(games)}return card}
function renderKo(ko,admin=false){koWege(ko);const card=document.createElement("article");card.className="ko-phase-card";card.innerHTML=`<h3>K.-o.-Baum ${ko.id}</h3>`;const wrap=document.createElement("div");wrap.className="gruppen-bracket";const grid=document.createElement("div");grid.className="gruppen-bracket-grid";ko.runden.forEach((runde,ri)=>{const col=document.createElement("section");col.className="gruppen-bracket-round";col.innerHTML=`<h4>Runde ${ri+1}</h4>`;runde.forEach(m=>{const e=koErgebnis(m),box=document.createElement("article");box.className="gruppen-bracket-match";box.innerHTML=`<small>${m.id}</small>`;[[m.a,m.scoreA],[m.b,m.scoreB]].forEach(([n,s])=>{const p=document.createElement("div");p.className="gruppen-bracket-player"+(e?.gewinner===n&&n!=="Freilos"?" winner":"");p.innerHTML=`<span>${n||"Noch offen"}</span><b>${s??"–"}</b>`;box.append(p)});if(admin&&m.a&&m.b&&m.a!=="Freilos"&&m.b!=="Freilos"){const row=document.createElement("div");row.className="gruppen-bracket-score";const na=document.createElement("span");na.textContent=m.a;const nb=document.createElement("span");nb.textContent=m.b;const sep=document.createElement("b");sep.textContent=":";const sa=scoreSelect(m.scoreA,v=>{m.scoreA=v;if(v===siegLegs()&&m.scoreB>=siegLegs())m.scoreB=null;koWege(ko);speichern();renderAlles()});const sb=scoreSelect(m.scoreB,v=>{m.scoreB=v;if(v===siegLegs()&&m.scoreA>=siegLegs())m.scoreA=null;koWege(ko);speichern();renderAlles()});row.append(na,sa,sep,sb,nb);box.append(row)}col.append(box)});grid.append(col)});wrap.append(grid);card.append(wrap);return card}
function renderAlles(){if(!daten||daten.modus!=="gruppenko")return;renderConfig();$("gruppenBereich")?.classList.remove("modus-versteckt");const pub=$("gruppenAnzeige");if(pub){pub.replaceChildren();daten.gruppen.forEach(g=>pub.append(renderGruppe(g,false)))}const adm=$("gruppenAdminAnzeige");if(adm){adm.replaceChildren();if(istAdmin)daten.gruppen.forEach(g=>adm.append(renderGruppe(g,true)))}const ko=$("gruppenKoAnzeige");if(ko){ko.replaceChildren();daten.koPhasen?.forEach(k=>ko.append(renderKo(k,istAdmin)));if(!daten.koPhasen?.length)ko.innerHTML='<p class="section-text">Die K.-o.-Bäume werden nach Abschluss der Gruppenphase erstellt.</p>'}const btn=$("koErstellenBtn");if(btn){btn.disabled=!alleGruppenFertig();btn.textContent=alleGruppenFertig()?"K.-o.-Phase erstellen":"Erst alle Gruppenspiele abschließen"}renderTv()}
function renderTv(){const gbox=$("tvGruppen");if(gbox){gbox.replaceChildren();daten?.gruppen?.forEach(g=>{const d=document.createElement("div");d.className="tv-gruppe";d.append(renderGruppe(g,false).querySelector("h3"),renderGruppe(g,false).querySelector("table"));gbox.append(d)})}const kbox=$("tvGruppenKo");if(kbox){kbox.replaceChildren();daten?.koPhasen?.forEach(k=>kbox.append(renderKo(k,false)))}}
function neuesGruppenTurnier(){const namen=teilnehmer.filter(p=>p.anwesend===true).map(spielName).filter(Boolean);const anzahl=Number($("gruppenAnzahl").value);if(namen.length<2){alert("Mindestens zwei anwesende Spieler werden benötigt.");return}if(anzahl>namen.length){alert("Es können nicht mehr Gruppen als Spieler erstellt werden.");return}daten={modus:"gruppenko",erstellt:Date.now(),bestOf:Number($("gruppenBestOf").value),anzahlGruppen:anzahl,anzahlKo:Number($("koAnzahl").value),regeln:clone(entwurfRegeln),gruppen:gruppenErstellen(namen,anzahl),koPhasen:[]};speichern();renderAlles()}

document.addEventListener("DOMContentLoaded",()=>{const mode=$("turnierModus");const originalBtn=$("turnierAuslosenBtn");mode?.addEventListener("change",()=>{localStorage.setItem("dart11enTurnierModus",mode.value);$("gruppenKonfiguration")?.classList.toggle("modus-versteckt",mode.value!=="gruppenko");originalBtn.textContent=mode.value==="gruppenko"?"🎲 Gruppen auslosen":"🎲 Live-Auslosung starten";renderConfig()});originalBtn?.addEventListener("click",e=>{if(mode?.value!=="gruppenko")return;e.stopImmediatePropagation();e.preventDefault();neuesGruppenTurnier()},true);$("koErstellenBtn")?.addEventListener("click",koPhasenErstellen);$("koAnzahl")?.addEventListener("change",()=>{if(!daten)return;daten.anzahlKo=Number($("koAnzahl").value);daten.koPhasen=[];speichern();renderAlles()});$("gruppenBestOf")?.addEventListener("change",()=>{if(!daten)return;daten.bestOf=Number($("gruppenBestOf").value);daten.gruppen.forEach(g=>g.spiele.forEach(m=>{m.scoreA=null;m.scoreB=null}));daten.koPhasen=[];speichern();renderAlles()});try{daten=JSON.parse(localStorage.getItem("dart11enGruppenKo")||"null")}catch{}if(daten){entwurfRegeln=clone(daten.regeln);renderAlles()}renderConfig();if(originalBtn&&mode)originalBtn.textContent=mode.value==="gruppenko"?"🎲 Gruppen auslosen":"🎲 Live-Auslosung starten"});
onSnapshot(collection(db,"warteschlange"),snap=>{teilnehmer=[];snap.forEach(d=>teilnehmer.push({id:d.id,...d.data()}))});
onSnapshot(doc(db,"turnierLive","gruppenTurnier"),snap=>{if(istAdmin&&!istTv)return;if(!snap.exists())return;try{daten=JSON.parse(snap.data().datenJson||"null");if(daten){localStorage.setItem("dart11enGruppenKo",JSON.stringify(daten));renderAlles()}}catch(e){console.error(e)}});
