import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-app.js";
import { getFirestore, doc, onSnapshot, setDoc } from "https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDtQ3pECcZETIoI4QTV5G-7_QcoRvVGHL4",authDomain:"dannistreffturnier.firebaseapp.com",projectId:"dannistreffturnier",storageBucket:"dannistreffturnier.firebasestorage.app",messagingSenderId:"829873084116",appId:"1:829873084116:web:683bbf1ea3e58f1a4ecd41",measurementId:"G-QEL7FSWMLG"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);
const db=getFirestore(app);
const THEME_DOC=doc(db,"einstellungen","vereinsdesign");
const LOCAL_KEY="dart11enVereinsdesignV507";
const defaults={clubName:"Dart11en",primary:"#e00022",secondary:"#0047ab",accent:"#ffbe2d",background:"#05070d",card:"#101116",text:"#ffffff",logoData:"dart11enlogo.png"};
let theme=loadLocal();
function loadLocal(){try{return {...defaults,...JSON.parse(localStorage.getItem(LOCAL_KEY)||"{}")}}catch{return {...defaults}}}
function isAdmin(){try{const x=JSON.parse(localStorage.getItem("dart11enLogin")||"null");return String(x?.rolle||sessionStorage.getItem("rolle")||"").toLowerCase().trim()==="admin"}catch{return String(sessionStorage.getItem("rolle")||"").toLowerCase().trim()==="admin"}}
function safeColor(value,fallback){return /^#[0-9a-f]{6}$/i.test(value||"")?value:fallback}
function applyTheme(next){theme={...defaults,...next};const r=document.documentElement.style;r.setProperty("--club-primary",safeColor(theme.primary,defaults.primary));r.setProperty("--club-secondary",safeColor(theme.secondary,defaults.secondary));r.setProperty("--club-accent",safeColor(theme.accent,defaults.accent));r.setProperty("--club-bg",safeColor(theme.background,defaults.background));r.setProperty("--club-card",safeColor(theme.card,defaults.card));r.setProperty("--club-text",safeColor(theme.text,defaults.text));
 const logo=theme.logoData||defaults.logoData;document.querySelectorAll('img[src="dart11enlogo.png"],[data-club-logo]').forEach(img=>{img.src=logo;img.dataset.clubLogo="1"});
 document.querySelectorAll("[data-club-name]").forEach(el=>el.textContent=theme.clubName||defaults.clubName);
 const preview=document.getElementById("themeLogoPreview");if(preview)preview.src=logo;
 syncInputs();localStorage.setItem(LOCAL_KEY,JSON.stringify(theme));window.dispatchEvent(new CustomEvent("dart11en-theme-changed",{detail:theme}));}
function syncInputs(){const ids={themeClubName:"clubName",themePrimary:"primary",themeSecondary:"secondary",themeAccent:"accent",themeBackground:"background",themeCard:"card",themeText:"text"};for(const [id,key] of Object.entries(ids)){const el=document.getElementById(id);if(el&&document.activeElement!==el)el.value=theme[key]||defaults[key]}}
function readFileAsOptimizedDataUrl(file){return new Promise((resolve,reject)=>{if(!file?.type?.startsWith("image/"))return reject(new Error("Bitte eine Bilddatei auswählen."));const reader=new FileReader();reader.onerror=()=>reject(new Error("Logo konnte nicht gelesen werden."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error("Logo ist ungültig."));img.onload=()=>{const max=512,scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.86))};img.src=reader.result};reader.readAsDataURL(file)})}
async function saveTheme(){const msg=document.getElementById("themeMessage");const next={clubName:document.getElementById("themeClubName")?.value.trim()||defaults.clubName,primary:document.getElementById("themePrimary")?.value||defaults.primary,secondary:document.getElementById("themeSecondary")?.value||defaults.secondary,accent:document.getElementById("themeAccent")?.value||defaults.accent,background:document.getElementById("themeBackground")?.value||defaults.background,card:document.getElementById("themeCard")?.value||defaults.card,text:document.getElementById("themeText")?.value||defaults.text,logoData:theme.logoData||defaults.logoData,updatedAt:new Date().toISOString()};applyTheme(next);if(msg)msg.textContent="Design wird gespeichert …";try{await setDoc(THEME_DOC,next,{merge:true});if(msg)msg.textContent="Vereinsdesign wurde für alle Geräte gespeichert."}catch(err){console.error(err);if(msg)msg.textContent="Design lokal gespeichert. Firebase hat die zentrale Speicherung abgelehnt."}}
async function resetTheme(){applyTheme(defaults);const msg=document.getElementById("themeMessage");try{await setDoc(THEME_DOC,{...defaults,updatedAt:new Date().toISOString()},{merge:true});if(msg)msg.textContent="Standarddesign wurde wiederhergestellt."}catch{if(msg)msg.textContent="Standarddesign wurde lokal wiederhergestellt."}}

document.addEventListener("DOMContentLoaded",()=>{applyTheme(theme);const admin=isAdmin();const group=document.getElementById("clubThemeSettings");if(group)group.hidden=!admin;
 ["themeClubName","themePrimary","themeSecondary","themeAccent","themeBackground","themeCard","themeText"].forEach(id=>document.getElementById(id)?.addEventListener("input",()=>{const draft={...theme,clubName:document.getElementById("themeClubName")?.value||theme.clubName,primary:document.getElementById("themePrimary")?.value||theme.primary,secondary:document.getElementById("themeSecondary")?.value||theme.secondary,accent:document.getElementById("themeAccent")?.value||theme.accent,background:document.getElementById("themeBackground")?.value||theme.background,card:document.getElementById("themeCard")?.value||theme.card,text:document.getElementById("themeText")?.value||theme.text};applyTheme(draft)}));
 document.getElementById("themeLogoInput")?.addEventListener("change",async e=>{const msg=document.getElementById("themeMessage");try{if(msg)msg.textContent="Logo wird verarbeitet …";theme.logoData=await readFileAsOptimizedDataUrl(e.target.files?.[0]);applyTheme(theme);if(msg)msg.textContent="Logo ist bereit. Jetzt Design speichern."}catch(err){if(msg)msg.textContent=err.message}});
 document.getElementById("themeLogoRemove")?.addEventListener("click",()=>{theme.logoData=defaults.logoData;applyTheme(theme)});
 document.getElementById("themeSaveBtn")?.addEventListener("click",saveTheme);document.getElementById("themeResetBtn")?.addEventListener("click",resetTheme);
 onSnapshot(THEME_DOC,snap=>{if(snap.exists())applyTheme(snap.data())},err=>console.warn("Vereinsdesign offline/lokal:",err));
});
